# Setup
title:               'Kushal Mishra'
tagline:             'A day at a time'
description:         'Shadowborne'
url:                 http://kushalmishra.github.io
baseurl:             /
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              'Kushal Mishra'
  url:               https://www.linkedin.com/in/kushal-mishra/
  email:             work.kushalmishra@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
